import type {
    ActivityGroup,
    ActivityLog,
    AttendanceSession,
    AttendanceSessionMember,
    AnnouncementItem,
    AuditLogEntry,
    Badge,
    Category,
    CorrectionRequest,
    Member,
    MemberBadge,
    RoleSummary,
    ScheduleEventItem,
    SeasonSummary,
    SiteBanner,
    TeamSummary,
} from '../../../types';

export type LocalMemberTeamLink = {
    id: string;
    memberId: string;
    teamId: string;
    createdAt: string;
};

type LocalState = {
    members: Member[];
    categories: Category[];
    activityGroups: ActivityGroup[];
    logs: ActivityLog[];
    auditLogs: AuditLogEntry[];
    correctionRequests: CorrectionRequest[];
    badges: Badge[];
    memberBadges: MemberBadge[];
    roles: RoleSummary[];
    teams: TeamSummary[];
    memberTeamLinks: LocalMemberTeamLink[];
    currentSeason: SeasonSummary;
    seasons: SeasonSummary[];
    announcements: AnnouncementItem[];
    scheduleEvents: ScheduleEventItem[];
    siteBanners: SiteBanner[];
    attendanceSessions: AttendanceSession[];
    attendanceSessionMembers: AttendanceSessionMember[];
};

const defaultActivityGroups: ActivityGroup[] = [
    { code: 'attendance', name: '출석', sortOrder: 10, isActive: true },
    { code: 'study', name: '스터디', sortOrder: 20, isActive: true },
    { code: 'contribution', name: '기여', sortOrder: 30, isActive: true },
    { code: 'operations', name: '운영', sortOrder: 40, isActive: true },
    { code: 'manual', name: '기타', sortOrder: 50, isActive: true },
];

const currentSeason: SeasonSummary = {
    id: 'season_2026_spring',
    name: '2026 상반기',
    status: 'active',
    startDate: '2026-03-01',
    endDate: '2026-08-31',
};

export const localState: LocalState = {
    members: [
        {
            id: 'm1',
            name: '이동섭',
            score: 180,
            loginEmail: 'leader@banollim.app',
            authUserId: 'auth_m1',
            authProvisionedAt: '2026-03-01T09:00:00.000Z',
            passwordResetRequired: false,
            isApproved: true,
            roleId: 'r1',
            roleName: '회장',
            teamId: 't1',
            teamName: '임원진',
            status: 'active',
            joinedAt: '2026-03-01',
            isVisible: true,
        },
        {
            id: 'm2',
            name: '김주영',
            score: 135,
            loginEmail: 'vice@banollim.app',
            authUserId: 'auth_m2',
            authProvisionedAt: '2026-03-01T09:10:00.000Z',
            passwordResetRequired: false,
            isApproved: true,
            roleId: 'r2',
            roleName: '부회장',
            teamId: 't1',
            teamName: '임원진',
            status: 'active',
            joinedAt: '2026-03-01',
            isVisible: true,
        },
        {
            id: 'm3',
            name: '김세현',
            score: 95,
            loginEmail: 'plan@banollim.app',
            authUserId: null,
            authProvisionedAt: null,
            passwordResetRequired: false,
            isApproved: true,
            roleId: 'r3',
            roleName: '기획팀장',
            teamId: 't2',
            teamName: '기획팀',
            status: 'active',
            joinedAt: '2026-03-02',
            isVisible: true,
        },
        {
            id: 'm4',
            name: '이민희',
            score: 40,
            loginEmail: null,
            authUserId: null,
            authProvisionedAt: null,
            passwordResetRequired: false,
            isApproved: false,
            roleId: null,
            roleName: '홍보팀장',
            teamId: 't3',
            teamName: '홍보팀',
            status: 'dormant',
            joinedAt: '2026-03-03',
            isVisible: true,
        },
    ],
    categories: [
        {
            id: 'p1',
            activityTypeId: 'at_attendance_present',
            categoryName: '정기모임 출석',
            groupName: 'attendance',
            pointValue: 10,
            penaltyPoint: 0,
            conditionSummary: '정시 참석 시 기본 점수 지급',
            conditionJson: { summary: '정시 참석 시 기본 점수 지급' },
            version: 1,
            isActive: true,
        },
        {
            id: 'p2',
            activityTypeId: 'at_study',
            categoryName: '스터디 참여',
            groupName: 'study',
            pointValue: 15,
            penaltyPoint: 0,
            conditionSummary: '스터디 출석 또는 실습 참여 완료',
            conditionJson: { summary: '스터디 출석 또는 실습 참여 완료' },
            version: 1,
            isActive: true,
        },
        {
            id: 'p3',
            activityTypeId: 'at_presentation',
            categoryName: '발표',
            groupName: 'contribution',
            pointValue: 30,
            penaltyPoint: 0,
            conditionSummary: '정기 발표 또는 세션 리딩',
            conditionJson: { summary: '정기 발표 또는 세션 리딩' },
            version: 2,
            isActive: true,
        },
        {
            id: 'p4',
            activityTypeId: 'at_attendance_late',
            categoryName: '지각',
            groupName: 'attendance',
            pointValue: -5,
            penaltyPoint: 5,
            conditionSummary: '정기모임 시작 이후 입장',
            conditionJson: { summary: '정기모임 시작 이후 입장' },
            version: 1,
            isActive: true,
        },
        {
            id: 'p5',
            activityTypeId: 'at_attendance_absent',
            categoryName: '불참',
            groupName: 'attendance',
            pointValue: 0,
            penaltyPoint: 0,
            conditionSummary: '사전 공유된 불참 처리 규칙 적용',
            conditionJson: { summary: '사전 공유된 불참 처리 규칙 적용' },
            version: 1,
            isActive: true,
        },
    ],
    activityGroups: [...defaultActivityGroups],
    logs: [
        {
            id: 'l1',
            recordId: 'record_l1',
            timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
            memberId: 'm1',
            categoryId: 'p1',
            pointDelta: 10,
            reason: '정기모임 출석',
            note: '주간 정기모임',
            evidenceUrl: 'https://example.com/attendance-sheet',
            recordStatus: 'confirmed',
        },
        {
            id: 'l2',
            recordId: 'record_l2',
            timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
            memberId: 'm2',
            categoryId: 'p3',
            pointDelta: 30,
            reason: '발표',
            note: 'AI 스터디 세션',
            evidenceUrl: 'https://example.com/slides/ai-study',
            recordStatus: 'confirmed',
        },
    ],
    auditLogs: [
        {
            id: 'audit_1',
            actorId: null,
            actorName: '로컬 운영자',
            entityType: 'activity_record',
            entityId: 'record_l1',
            action: 'created',
            summary: '이동섭 · 정기모임 출석 기록 생성',
            createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
            diff: {
                memberId: 'm1',
                memberName: '이동섭',
                pointRuleId: 'p1',
                ruleName: '정기모임 출석',
                delta: 10,
                reason: '정기모임 출석',
            },
        },
        {
            id: 'audit_2',
            actorId: null,
            actorName: '로컬 운영자',
            entityType: 'activity_record',
            entityId: 'record_l2',
            action: 'created',
            summary: '김주영 · 발표 기록 생성',
            createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
            diff: {
                memberId: 'm2',
                memberName: '김주영',
                pointRuleId: 'p3',
                ruleName: '발표',
                delta: 30,
                reason: '발표',
            },
        },
    ],
    correctionRequests: [
        {
            id: 'correction_1',
            requesterMemberId: 'm1',
            requesterName: '이동섭',
            activityRecordId: 'record_l1',
            status: 'pending',
            reason: '주간 정기모임이 아니라 월간 전체모임 출석으로 기록되어 메모 수정이 필요합니다.',
            reviewNote: null,
            reviewedBy: null,
            reviewedByName: null,
            reviewedAt: null,
            createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
            updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
            activitySummary: '정기모임 출석',
            activityOccurredAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
            activityPointDelta: 10,
        },
    ],
    badges: [
        {
            id: 'badge_first_step',
            code: 'first_step',
            name: '첫 발자국',
            description: '첫 활동 기록을 남겼습니다.',
            iconKey: 'bandi-core',
            imageUrl: null,
            tone: 'gold',
            evaluationScope: 'season',
            criteria: { activityCount: 1 },
            sortOrder: 10,
            isActive: true,
        },
        {
            id: 'badge_steady_rhythm',
            code: 'steady_rhythm',
            name: '꾸준한 리듬',
            description: '서로 다른 날짜에 3회 이상 활동을 이어갔습니다.',
            iconKey: 'bandi-orbit',
            imageUrl: null,
            tone: 'emerald',
            evaluationScope: 'season',
            criteria: { activeDayCount: 3 },
            sortOrder: 20,
            isActive: true,
        },
        {
            id: 'badge_attendance_radar',
            code: 'attendance_radar',
            name: '출석 레이더',
            description: '출석 계열 활동을 5회 이상 기록했습니다.',
            iconKey: 'school-signal',
            imageUrl: null,
            tone: 'sky',
            evaluationScope: 'season',
            criteria: { attendanceCount: 5 },
            sortOrder: 30,
            isActive: true,
        },
        {
            id: 'badge_spotlight',
            code: 'spotlight',
            name: '스포트라이트',
            description: '발표 또는 고점수 기여를 남겼습니다.',
            iconKey: 'bandi-flash',
            imageUrl: null,
            tone: 'rose',
            evaluationScope: 'season',
            criteria: { spotlightCount: 1 },
            sortOrder: 40,
            isActive: true,
        },
        {
            id: 'badge_multi_tool',
            code: 'multi_tool',
            name: '멀티 플레이어',
            description: '서로 다른 활동 유형 4개 이상을 경험했습니다.',
            iconKey: 'didi-toolkit',
            imageUrl: null,
            tone: 'sky',
            evaluationScope: 'season',
            criteria: { uniqueActivityTypeCount: 4 },
            sortOrder: 50,
            isActive: true,
        },
        {
            id: 'badge_archive_keeper',
            code: 'archive_keeper',
            name: '기록 보관자',
            description: '증빙 링크가 포함된 활동을 2건 이상 남겼습니다.',
            iconKey: 'didi-archive',
            imageUrl: null,
            tone: 'emerald',
            evaluationScope: 'season',
            criteria: { evidenceCount: 2 },
            sortOrder: 60,
            isActive: true,
        },
    ],
    memberBadges: [],
    roles: [
        { id: 'r1', name: '회장', permissionScope: 'super_admin', rankOrder: 10 },
        { id: 'r2', name: '부회장', permissionScope: 'operator', rankOrder: 20 },
        { id: 'r3', name: '기획팀장', permissionScope: 'operator', rankOrder: 30 },
        { id: 'r4', name: '일반회원', permissionScope: 'member', rankOrder: 100 },
    ],
    teams: [
        { id: 't1', name: '임원진', type: 'core', isActive: true },
        { id: 't2', name: '기획팀', type: 'core', isActive: true },
        { id: 't3', name: '홍보팀', type: 'core', isActive: true },
        { id: 't4', name: '운영팀', type: 'core', isActive: true },
        { id: 't5', name: '스터디', type: 'study', isActive: true },
    ],
    memberTeamLinks: [],
    currentSeason,
    seasons: [
        currentSeason,
        {
            id: 'season_2025_fall',
            name: '2025 하반기',
            status: 'closed',
            startDate: '2025-09-01',
            endDate: '2026-02-28',
        },
    ],
    announcements: [
        {
            id: 'notice_1',
            title: '3월 정기모임 운영 안내',
            body: '이번 주 정기모임은 활동 리캡 공유와 시즌 출석 규칙 안내를 함께 진행합니다.',
            startAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
            endAt: null,
            isPinned: true,
            isActive: true,
            createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
        },
        {
            id: 'notice_2',
            title: '발표 자료 제출 마감',
            body: '발표자는 모임 전날 밤 10시까지 자료 링크를 제출해 주세요.',
            startAt: new Date().toISOString(),
            endAt: null,
            isPinned: false,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
    ],
    scheduleEvents: [
        {
            id: 'schedule_1',
            title: '정기모임 오프라인 세션',
            description: '출석 체크와 시즌 규칙 설명, 팀별 브리핑을 진행합니다.',
            location: '반디스쿨 3층 세미나실',
            startAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2).toISOString(),
            endAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2 + 1000 * 60 * 90).toISOString(),
            seasonId: currentSeason.id,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
        {
            id: 'schedule_2',
            title: '운영진 주간 체크인',
            description: '승인 대기, 정정 요청, 리캡 공유 카드 현황을 점검합니다.',
            location: '온라인 미트',
            startAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 4).toISOString(),
            endAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 4 + 1000 * 60 * 45).toISOString(),
            seasonId: currentSeason.id,
            isActive: true,
            createdAt: new Date().toISOString(),
        },
    ],
    siteBanners: [],
    attendanceSessions: [],
    attendanceSessionMembers: [],
};

localState.memberTeamLinks = localState.members
    .filter((member) => member.teamId)
    .map((member, index) => ({
        id: `member_team_${index + 1}`,
        memberId: member.id,
        teamId: member.teamId!,
        createdAt: new Date().toISOString(),
    }));
